-- Create "organizations" table
CREATE TABLE "organizations" ("id" uuid NOT NULL DEFAULT gen_random_uuid(), "name" text NOT NULL, "slug" text NOT NULL, "plan" text NOT NULL DEFAULT 'trial', "created_at" timestamptz NOT NULL DEFAULT now(), "updated_at" timestamptz NOT NULL DEFAULT now(), PRIMARY KEY ("id"), CONSTRAINT "organizations_slug_key" UNIQUE ("slug"));
-- Create "students" table
CREATE TABLE "students" ("id" uuid NOT NULL DEFAULT gen_random_uuid(), "org_id" uuid NOT NULL, "name" text NOT NULL, "phone" text NULL, "telegram_id" text NULL, "telegram_chat_id" bigint NULL, "course_name" text NULL, "group_name" text NULL, "mentor_name" text NULL, "start_date" date NULL, "onboarding_goal" text NULL, "six_month_target" text NULL, "weekly_study_hours" text NULL, "confidence_level" integer NOT NULL DEFAULT 5, "risk_score" integer NOT NULL DEFAULT 0, "risk_tier" text NOT NULL DEFAULT 'Green', "created_at" timestamptz NOT NULL DEFAULT now(), "updated_at" timestamptz NOT NULL DEFAULT now(), PRIMARY KEY ("id"), CONSTRAINT "students_org_id_fkey" FOREIGN KEY ("org_id") REFERENCES "organizations" ("id") ON UPDATE NO ACTION ON DELETE CASCADE);
-- Create index "idx_students_org" to table: "students"
CREATE INDEX "idx_students_org" ON "students" ("org_id");
-- Create index "idx_students_org_risk" to table: "students"
CREATE INDEX "idx_students_org_risk" ON "students" ("org_id", "risk_score" DESC);
-- Create "attendance_records" table
CREATE TABLE "attendance_records" ("id" uuid NOT NULL DEFAULT gen_random_uuid(), "org_id" uuid NOT NULL, "student_id" uuid NOT NULL, "date" date NOT NULL, "is_present" boolean NOT NULL, "created_at" timestamptz NOT NULL DEFAULT now(), PRIMARY KEY ("id"), CONSTRAINT "attendance_records_org_id_fkey" FOREIGN KEY ("org_id") REFERENCES "organizations" ("id") ON UPDATE NO ACTION ON DELETE CASCADE, CONSTRAINT "attendance_records_student_id_fkey" FOREIGN KEY ("student_id") REFERENCES "students" ("id") ON UPDATE NO ACTION ON DELETE CASCADE);
-- Create index "idx_attendance_student" to table: "attendance_records"
CREATE INDEX "idx_attendance_student" ON "attendance_records" ("student_id");
-- Create "bot_conversations" table
CREATE TABLE "bot_conversations" ("id" uuid NOT NULL DEFAULT gen_random_uuid(), "org_id" uuid NULL, "telegram_chat_id" bigint NOT NULL, "student_id" uuid NULL, "flow" text NULL, "step" text NULL, "state" jsonb NOT NULL DEFAULT '{}', "updated_at" timestamptz NOT NULL DEFAULT now(), PRIMARY KEY ("id"), CONSTRAINT "bot_conversations_telegram_chat_id_key" UNIQUE ("telegram_chat_id"), CONSTRAINT "bot_conversations_org_id_fkey" FOREIGN KEY ("org_id") REFERENCES "organizations" ("id") ON UPDATE NO ACTION ON DELETE CASCADE, CONSTRAINT "bot_conversations_student_id_fkey" FOREIGN KEY ("student_id") REFERENCES "students" ("id") ON UPDATE NO ACTION ON DELETE SET NULL);
-- Create "intervention_tasks" table
CREATE TABLE "intervention_tasks" ("id" uuid NOT NULL DEFAULT gen_random_uuid(), "org_id" uuid NOT NULL, "student_id" uuid NOT NULL, "reasons" text[] NOT NULL DEFAULT '{}', "status" text NOT NULL DEFAULT 'Open', "resolution_comment" text NULL, "created_at" timestamptz NOT NULL DEFAULT now(), "resolved_at" timestamptz NULL, PRIMARY KEY ("id"), CONSTRAINT "intervention_tasks_org_id_fkey" FOREIGN KEY ("org_id") REFERENCES "organizations" ("id") ON UPDATE NO ACTION ON DELETE CASCADE, CONSTRAINT "intervention_tasks_student_id_fkey" FOREIGN KEY ("student_id") REFERENCES "students" ("id") ON UPDATE NO ACTION ON DELETE CASCADE);
-- Create index "idx_tasks_org_status" to table: "intervention_tasks"
CREATE INDEX "idx_tasks_org_status" ON "intervention_tasks" ("org_id", "status");
-- Create "users" table
CREATE TABLE "users" ("id" uuid NOT NULL DEFAULT gen_random_uuid(), "org_id" uuid NOT NULL, "email" text NOT NULL, "password_hash" text NOT NULL, "full_name" text NOT NULL, "role" text NOT NULL DEFAULT 'mentor', "created_at" timestamptz NOT NULL DEFAULT now(), "updated_at" timestamptz NOT NULL DEFAULT now(), PRIMARY KEY ("id"), CONSTRAINT "users_org_id_email_key" UNIQUE ("org_id", "email"), CONSTRAINT "users_org_id_fkey" FOREIGN KEY ("org_id") REFERENCES "organizations" ("id") ON UPDATE NO ACTION ON DELETE CASCADE);
-- Create "invite_tokens" table
CREATE TABLE "invite_tokens" ("token" text NOT NULL, "org_id" uuid NOT NULL, "created_by" uuid NULL, "used_at" timestamptz NULL, "expires_at" timestamptz NOT NULL, "created_at" timestamptz NOT NULL DEFAULT now(), PRIMARY KEY ("token"), CONSTRAINT "invite_tokens_created_by_fkey" FOREIGN KEY ("created_by") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE SET NULL, CONSTRAINT "invite_tokens_org_id_fkey" FOREIGN KEY ("org_id") REFERENCES "organizations" ("id") ON UPDATE NO ACTION ON DELETE CASCADE);
-- Create "notes" table
CREATE TABLE "notes" ("id" uuid NOT NULL DEFAULT gen_random_uuid(), "org_id" uuid NOT NULL, "student_id" uuid NOT NULL, "author" text NOT NULL, "text" text NOT NULL, "created_at" timestamptz NOT NULL DEFAULT now(), PRIMARY KEY ("id"), CONSTRAINT "notes_org_id_fkey" FOREIGN KEY ("org_id") REFERENCES "organizations" ("id") ON UPDATE NO ACTION ON DELETE CASCADE, CONSTRAINT "notes_student_id_fkey" FOREIGN KEY ("student_id") REFERENCES "students" ("id") ON UPDATE NO ACTION ON DELETE CASCADE);
-- Create index "idx_notes_student" to table: "notes"
CREATE INDEX "idx_notes_student" ON "notes" ("student_id");
-- Create "refresh_sessions" table
CREATE TABLE "refresh_sessions" ("id" uuid NOT NULL DEFAULT gen_random_uuid(), "user_id" uuid NOT NULL, "org_id" uuid NOT NULL, "token_hash" text NOT NULL, "user_agent" text NULL, "ip" text NULL, "expires_at" timestamptz NOT NULL, "revoked_at" timestamptz NULL, "created_at" timestamptz NOT NULL DEFAULT now(), PRIMARY KEY ("id"), CONSTRAINT "refresh_sessions_token_hash_key" UNIQUE ("token_hash"), CONSTRAINT "refresh_sessions_org_id_fkey" FOREIGN KEY ("org_id") REFERENCES "organizations" ("id") ON UPDATE NO ACTION ON DELETE CASCADE, CONSTRAINT "refresh_sessions_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE CASCADE);
-- Create index "idx_refresh_sessions_user" to table: "refresh_sessions"
CREATE INDEX "idx_refresh_sessions_user" ON "refresh_sessions" ("user_id");
-- Create "surveys" table
CREATE TABLE "surveys" ("id" uuid NOT NULL DEFAULT gen_random_uuid(), "org_id" uuid NOT NULL, "student_id" uuid NOT NULL, "week_number" integer NOT NULL, "motivation_score" integer NOT NULL, "progress_score" integer NOT NULL, "biggest_obstacle" text NULL, "comment" text NULL, "submitted_at" timestamptz NOT NULL DEFAULT now(), PRIMARY KEY ("id"), CONSTRAINT "surveys_org_id_fkey" FOREIGN KEY ("org_id") REFERENCES "organizations" ("id") ON UPDATE NO ACTION ON DELETE CASCADE, CONSTRAINT "surveys_student_id_fkey" FOREIGN KEY ("student_id") REFERENCES "students" ("id") ON UPDATE NO ACTION ON DELETE CASCADE);
-- Create index "idx_surveys_student" to table: "surveys"
CREATE INDEX "idx_surveys_student" ON "surveys" ("student_id");
