// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Activity struct {
	ID          uuid.UUID          `json:"id"`
	OrgID       uuid.UUID          `json:"org_id"`
	SubjectType string             `json:"subject_type"`
	SubjectID   uuid.UUID          `json:"subject_id"`
	Type        string             `json:"type"`
	Body        string             `json:"body"`
	Author      string             `json:"author"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type AiAdviceFeedback struct {
	ID        uuid.UUID          `json:"id"`
	OrgID     uuid.UUID          `json:"org_id"`
	StudentID uuid.UUID          `json:"student_id"`
	UserID    uuid.UUID          `json:"user_id"`
	Useful    bool               `json:"useful"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type AttendanceRecord struct {
	ID        uuid.UUID          `json:"id"`
	OrgID     uuid.UUID          `json:"org_id"`
	StudentID uuid.UUID          `json:"student_id"`
	GroupID   pgtype.UUID        `json:"group_id"`
	Date      pgtype.Date        `json:"date"`
	IsPresent bool               `json:"is_present"`
	Status    string             `json:"status"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type BotConversation struct {
	ID             uuid.UUID          `json:"id"`
	OrgID          pgtype.UUID        `json:"org_id"`
	TelegramChatID int64              `json:"telegram_chat_id"`
	StudentID      pgtype.UUID        `json:"student_id"`
	Flow           pgtype.Text        `json:"flow"`
	Step           pgtype.Text        `json:"step"`
	State          []byte             `json:"state"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type Branch struct {
	ID        uuid.UUID          `json:"id"`
	OrgID     uuid.UUID          `json:"org_id"`
	Name      string             `json:"name"`
	Address   string             `json:"address"`
	Phone     string             `json:"phone"`
	IsActive  bool               `json:"is_active"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Course struct {
	ID            uuid.UUID          `json:"id"`
	OrgID         uuid.UUID          `json:"org_id"`
	Name          string             `json:"name"`
	Code          string             `json:"code"`
	Level         string             `json:"level"`
	Price         int64              `json:"price"`
	DurationWeeks int32              `json:"duration_weeks"`
	Description   string             `json:"description"`
	IsActive      bool               `json:"is_active"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type Enrollment struct {
	ID        uuid.UUID          `json:"id"`
	OrgID     uuid.UUID          `json:"org_id"`
	StudentID uuid.UUID          `json:"student_id"`
	GroupID   pgtype.UUID        `json:"group_id"`
	CourseID  pgtype.UUID        `json:"course_id"`
	Status    string             `json:"status"`
	StartDate pgtype.Date        `json:"start_date"`
	EndDate   pgtype.Date        `json:"end_date"`
	Price     int64              `json:"price"`
	Discount  int32              `json:"discount"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Expense struct {
	ID        uuid.UUID          `json:"id"`
	OrgID     uuid.UUID          `json:"org_id"`
	Category  string             `json:"category"`
	Amount    int64              `json:"amount"`
	SpentAt   pgtype.Date        `json:"spent_at"`
	Note      string             `json:"note"`
	BranchID  pgtype.UUID        `json:"branch_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Group struct {
	ID           uuid.UUID          `json:"id"`
	OrgID        uuid.UUID          `json:"org_id"`
	Name         string             `json:"name"`
	TeacherID    pgtype.UUID        `json:"teacher_id"`
	CourseID     pgtype.UUID        `json:"course_id"`
	BranchID     pgtype.UUID        `json:"branch_id"`
	Direction    pgtype.Text        `json:"direction"`
	ScheduleDays pgtype.Text        `json:"schedule_days"`
	Capacity     int32              `json:"capacity"`
	StartDate    pgtype.Date        `json:"start_date"`
	EndDate      pgtype.Date        `json:"end_date"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	StartTime    string             `json:"start_time"`
	EndTime      string             `json:"end_time"`
	RoomID       pgtype.UUID        `json:"room_id"`
}

type GroupMember struct {
	ID        uuid.UUID          `json:"id"`
	OrgID     uuid.UUID          `json:"org_id"`
	GroupID   uuid.UUID          `json:"group_id"`
	StudentID uuid.UUID          `json:"student_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type HomeworkRecord struct {
	ID        uuid.UUID          `json:"id"`
	OrgID     uuid.UUID          `json:"org_id"`
	StudentID uuid.UUID          `json:"student_id"`
	Date      pgtype.Date        `json:"date"`
	IsDone    bool               `json:"is_done"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type InterventionTask struct {
	ID                uuid.UUID          `json:"id"`
	OrgID             uuid.UUID          `json:"org_id"`
	StudentID         uuid.UUID          `json:"student_id"`
	Reasons           []string           `json:"reasons"`
	Status            string             `json:"status"`
	ResolutionComment pgtype.Text        `json:"resolution_comment"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	ResolvedAt        pgtype.Timestamptz `json:"resolved_at"`
}

type InviteToken struct {
	Token     string             `json:"token"`
	OrgID     uuid.UUID          `json:"org_id"`
	StudentID pgtype.UUID        `json:"student_id"`
	CreatedBy pgtype.UUID        `json:"created_by"`
	UsedAt    pgtype.Timestamptz `json:"used_at"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Invoice struct {
	ID           uuid.UUID          `json:"id"`
	OrgID        uuid.UUID          `json:"org_id"`
	StudentID    uuid.UUID          `json:"student_id"`
	GroupID      pgtype.UUID        `json:"group_id"`
	EnrollmentID pgtype.UUID        `json:"enrollment_id"`
	Amount       int64              `json:"amount"`
	PaidAmount   int64              `json:"paid_amount"`
	DueDate      pgtype.Date        `json:"due_date"`
	Period       string             `json:"period"`
	Note         string             `json:"note"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type Lead struct {
	ID         uuid.UUID          `json:"id"`
	OrgID      uuid.UUID          `json:"org_id"`
	Name       string             `json:"name"`
	Phone      pgtype.Text        `json:"phone"`
	Email      pgtype.Text        `json:"email"`
	Source     string             `json:"source"`
	Stage      string             `json:"stage"`
	Interest   string             `json:"interest"`
	Note       string             `json:"note"`
	AssignedTo pgtype.UUID        `json:"assigned_to"`
	StudentID  pgtype.UUID        `json:"student_id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type Lesson struct {
	ID        uuid.UUID          `json:"id"`
	OrgID     uuid.UUID          `json:"org_id"`
	GroupID   pgtype.UUID        `json:"group_id"`
	TeacherID pgtype.UUID        `json:"teacher_id"`
	Date      pgtype.Date        `json:"date"`
	StartTime string             `json:"start_time"`
	EndTime   string             `json:"end_time"`
	Room      string             `json:"room"`
	RoomID    pgtype.UUID        `json:"room_id"`
	Topic     string             `json:"topic"`
	Status    string             `json:"status"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Note struct {
	ID        uuid.UUID          `json:"id"`
	OrgID     uuid.UUID          `json:"org_id"`
	StudentID uuid.UUID          `json:"student_id"`
	Author    string             `json:"author"`
	Text      string             `json:"text"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type ObstacleOption struct {
	ID        uuid.UUID          `json:"id"`
	OrgID     uuid.UUID          `json:"org_id"`
	Label     string             `json:"label"`
	Position  int32              `json:"position"`
	IsActive  bool               `json:"is_active"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Organization struct {
	ID            uuid.UUID          `json:"id"`
	Name          string             `json:"name"`
	Slug          string             `json:"slug"`
	Plan          string             `json:"plan"`
	Status        string             `json:"status"`
	TrialEndsAt   pgtype.Timestamptz `json:"trial_ends_at"`
	BillingStatus string             `json:"billing_status"`
	GraceLessons  int32              `json:"grace_lessons"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type Payment struct {
	ID        uuid.UUID          `json:"id"`
	OrgID     uuid.UUID          `json:"org_id"`
	InvoiceID uuid.UUID          `json:"invoice_id"`
	StudentID uuid.UUID          `json:"student_id"`
	Amount    int64              `json:"amount"`
	Method    string             `json:"method"`
	PaidAt    pgtype.Timestamptz `json:"paid_at"`
	Note      string             `json:"note"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Plan struct {
	ID          uuid.UUID          `json:"id"`
	PlanKey     string             `json:"plan_key"`
	Name        string             `json:"name"`
	Price       string             `json:"price"`
	Period      string             `json:"period"`
	Tagline     string             `json:"tagline"`
	Features    []string           `json:"features"`
	Highlighted bool               `json:"highlighted"`
	SortOrder   int32              `json:"sort_order"`
	IsActive    bool               `json:"is_active"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type RefreshSession struct {
	ID        uuid.UUID          `json:"id"`
	UserID    uuid.UUID          `json:"user_id"`
	OrgID     uuid.UUID          `json:"org_id"`
	TokenHash string             `json:"token_hash"`
	UserAgent pgtype.Text        `json:"user_agent"`
	Ip        pgtype.Text        `json:"ip"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Room struct {
	ID        uuid.UUID          `json:"id"`
	OrgID     uuid.UUID          `json:"org_id"`
	BranchID  pgtype.UUID        `json:"branch_id"`
	Name      string             `json:"name"`
	Capacity  int32              `json:"capacity"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type SalaryGroupRule struct {
	ID        uuid.UUID          `json:"id"`
	OrgID     uuid.UUID          `json:"org_id"`
	TeacherID uuid.UUID          `json:"teacher_id"`
	GroupID   uuid.UUID          `json:"group_id"`
	Kind      string             `json:"kind"`
	Rate      int64              `json:"rate"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type SalaryRule struct {
	ID         uuid.UUID          `json:"id"`
	OrgID      uuid.UUID          `json:"org_id"`
	TeacherID  uuid.UUID          `json:"teacher_id"`
	Kind       string             `json:"kind"`
	Rate       int64              `json:"rate"`
	BaseAmount int64              `json:"base_amount"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type SalarySlip struct {
	ID          uuid.UUID          `json:"id"`
	OrgID       uuid.UUID          `json:"org_id"`
	TeacherID   uuid.UUID          `json:"teacher_id"`
	PeriodStart pgtype.Date        `json:"period_start"`
	PeriodEnd   pgtype.Date        `json:"period_end"`
	Gross       int64              `json:"gross"`
	Bonus       int64              `json:"bonus"`
	Deduction   int64              `json:"deduction"`
	Net         int64              `json:"net"`
	Status      string             `json:"status"`
	Note        string             `json:"note"`
	PaidAt      pgtype.Timestamptz `json:"paid_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type SignupRequest struct {
	ID          uuid.UUID          `json:"id"`
	CenterName  string             `json:"center_name"`
	ContactName string             `json:"contact_name"`
	Phone       string             `json:"phone"`
	Email       string             `json:"email"`
	Plan        string             `json:"plan"`
	Message     string             `json:"message"`
	Status      string             `json:"status"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Student struct {
	ID               uuid.UUID          `json:"id"`
	OrgID            uuid.UUID          `json:"org_id"`
	Name             string             `json:"name"`
	Phone            pgtype.Text        `json:"phone"`
	TelegramID       pgtype.Text        `json:"telegram_id"`
	TelegramChatID   pgtype.Int8        `json:"telegram_chat_id"`
	CourseName       pgtype.Text        `json:"course_name"`
	GroupName        pgtype.Text        `json:"group_name"`
	GroupID          pgtype.UUID        `json:"group_id"`
	MentorName       pgtype.Text        `json:"mentor_name"`
	StartDate        pgtype.Date        `json:"start_date"`
	OnboardingGoal   pgtype.Text        `json:"onboarding_goal"`
	SixMonthTarget   pgtype.Text        `json:"six_month_target"`
	WeeklyStudyHours pgtype.Text        `json:"weekly_study_hours"`
	ConfidenceLevel  int32              `json:"confidence_level"`
	RiskScore        int32              `json:"risk_score"`
	RiskTier         string             `json:"risk_tier"`
	Email            pgtype.Text        `json:"email"`
	BirthDate        pgtype.Date        `json:"birth_date"`
	Gender           string             `json:"gender"`
	SecondPhone      pgtype.Text        `json:"second_phone"`
	Address          pgtype.Text        `json:"address"`
	ParentName       pgtype.Text        `json:"parent_name"`
	ParentPhone      pgtype.Text        `json:"parent_phone"`
	StudentCode      pgtype.Text        `json:"student_code"`
	Status           string             `json:"status"`
	MentorID         pgtype.UUID        `json:"mentor_id"`
	BranchID         pgtype.UUID        `json:"branch_id"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type Survey struct {
	ID              uuid.UUID          `json:"id"`
	OrgID           uuid.UUID          `json:"org_id"`
	StudentID       uuid.UUID          `json:"student_id"`
	WeekNumber      int32              `json:"week_number"`
	MotivationScore int32              `json:"motivation_score"`
	ProgressScore   int32              `json:"progress_score"`
	BiggestObstacle pgtype.Text        `json:"biggest_obstacle"`
	Comment         pgtype.Text        `json:"comment"`
	SubmittedAt     pgtype.Timestamptz `json:"submitted_at"`
}

type User struct {
	ID           uuid.UUID          `json:"id"`
	OrgID        uuid.UUID          `json:"org_id"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	FullName     string             `json:"full_name"`
	Role         string             `json:"role"`
	Phone        pgtype.Text        `json:"phone"`
	IsActive     bool               `json:"is_active"`
	BranchID     pgtype.UUID        `json:"branch_id"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}
