// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AdjustInvoicePaid(ctx context.Context, arg AdjustInvoicePaidParams) error
	// Sets group_id AND denormalizes group_name to the group's name (or '' when unassigning), so the
	// legacy group_name field stays in sync — the student list + dashboard read group_name.
	AssignStudentGroup(ctx context.Context, arg AssignStudentGroupParams) error
	AvgMotivationByWeek(ctx context.Context) ([]AvgMotivationByWeekRow, error)
	BindBotChat(ctx context.Context, arg BindBotChatParams) (BotConversation, error)
	CountOpenTasksForStudent(ctx context.Context, studentID uuid.UUID) (int64, error)
	// Room double-booking: same room + date with time overlap (existing.start < new.end AND
	// existing.end > new.start). Excludes cancelled lessons, timeless lessons, and the given id (self).
	CountRoomConflicts(ctx context.Context, arg CountRoomConflictsParams) (int64, error)
	// --- dashboard aggregates (RLS-scoped: run inside WithTenant) ---
	CountStudentsByTier(ctx context.Context) ([]CountStudentsByTierRow, error)
	CountStudentsInGroup(ctx context.Context, groupID pgtype.UUID) (int64, error)
	// RLS-scoped: run inside WithTenant(org).
	CountStudentsInOrg(ctx context.Context) (int64, error)
	CountTeacherActiveStudents(ctx context.Context, dollar_1 uuid.UUID) (int64, error)
	CountTeacherDoneLessons(ctx context.Context, arg CountTeacherDoneLessonsParams) (int64, error)
	// RLS-scoped: run inside WithTenant(org).
	CountUsersInOrg(ctx context.Context) (int64, error)
	CreateActivity(ctx context.Context, arg CreateActivityParams) (Activity, error)
	CreateAdviceFeedback(ctx context.Context, arg CreateAdviceFeedbackParams) error
	CreateAttendance(ctx context.Context, arg CreateAttendanceParams) (AttendanceRecord, error)
	CreateBranch(ctx context.Context, arg CreateBranchParams) (Branch, error)
	CreateCourse(ctx context.Context, arg CreateCourseParams) (Course, error)
	CreateEnrollment(ctx context.Context, arg CreateEnrollmentParams) (Enrollment, error)
	CreateExpense(ctx context.Context, arg CreateExpenseParams) (Expense, error)
	// --- groups (RLS-scoped: run inside WithTenant) ---
	CreateGroup(ctx context.Context, arg CreateGroupParams) (Group, error)
	CreateHomework(ctx context.Context, arg CreateHomeworkParams) (HomeworkRecord, error)
	// ON CONFLICT DO NOTHING (against the one-open-per-student partial index) makes this
	// idempotent WITHOUT raising 23505, which would otherwise abort the surrounding tx.
	// A conflict (a task is already open) returns no row → pgx.ErrNoRows for the caller.
	CreateInterventionTask(ctx context.Context, arg CreateInterventionTaskParams) (InterventionTask, error)
	// --- telegram bot (invite_tokens + bot_conversations are NON-RLS: the bot resolves them with
	// no tenant scope, by secret token or unique chat_id, then enters WithTenant for student writes) ---
	CreateInviteToken(ctx context.Context, arg CreateInviteTokenParams) (InviteToken, error)
	CreateInvoice(ctx context.Context, arg CreateInvoiceParams) (Invoice, error)
	CreateLead(ctx context.Context, arg CreateLeadParams) (Lead, error)
	CreateLesson(ctx context.Context, arg CreateLessonParams) (Lesson, error)
	CreateNote(ctx context.Context, arg CreateNoteParams) (Note, error)
	CreateObstacleOption(ctx context.Context, arg CreateObstacleOptionParams) (ObstacleOption, error)
	// sqlc queries. Run `make sqlc` to regenerate internal/repo/sqlc.
	//
	// Tenant tables (users, students, …) have NO "WHERE org_id" clause: callers run them
	// inside platform/postgres.WithTenant, and RLS filters every row. org_id is set on INSERT.
	// organizations and refresh_sessions are NOT under RLS (looked up before org scope exists).
	CreateOrganization(ctx context.Context, arg CreateOrganizationParams) (Organization, error)
	CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error)
	CreatePlan(ctx context.Context, arg CreatePlanParams) (Plan, error)
	CreateRefreshSession(ctx context.Context, arg CreateRefreshSessionParams) (RefreshSession, error)
	CreateRoom(ctx context.Context, arg CreateRoomParams) (Room, error)
	CreateSalarySlip(ctx context.Context, arg CreateSalarySlipParams) (SalarySlip, error)
	CreateSignupRequest(ctx context.Context, arg CreateSignupRequestParams) (SignupRequest, error)
	// --- students + notes (RLS-scoped: run inside WithTenant; no WHERE org_id) ---
	CreateStudent(ctx context.Context, arg CreateStudentParams) (Student, error)
	// --- surveys + attendance + intervention tasks (RLS-scoped: run inside WithTenant) ---
	CreateSurvey(ctx context.Context, arg CreateSurveyParams) (Survey, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteActivity(ctx context.Context, arg DeleteActivityParams) error
	DeleteBranch(ctx context.Context, id uuid.UUID) error
	DeleteCourse(ctx context.Context, arg DeleteCourseParams) error
	DeleteEnrollment(ctx context.Context, arg DeleteEnrollmentParams) error
	DeleteExpense(ctx context.Context, id uuid.UUID) error
	DeleteExpiredRefreshSessions(ctx context.Context) error
	DeleteGroup(ctx context.Context, id uuid.UUID) error
	DeleteInvoice(ctx context.Context, arg DeleteInvoiceParams) error
	DeleteLead(ctx context.Context, arg DeleteLeadParams) error
	DeleteLesson(ctx context.Context, arg DeleteLessonParams) error
	DeleteObstacleOption(ctx context.Context, arg DeleteObstacleOptionParams) error
	DeleteOrganization(ctx context.Context, id uuid.UUID) error
	DeletePayment(ctx context.Context, arg DeletePaymentParams) error
	DeletePlan(ctx context.Context, id uuid.UUID) error
	DeleteRoom(ctx context.Context, id uuid.UUID) error
	DeleteSalarySlip(ctx context.Context, id uuid.UUID) error
	DeleteStudent(ctx context.Context, id uuid.UUID) error
	DeleteTeacher(ctx context.Context, id uuid.UUID) error
	ExpensesByCategory(ctx context.Context, arg ExpensesByCategoryParams) ([]ExpensesByCategoryRow, error)
	FinanceSummary(ctx context.Context, dollar_1 uuid.UUID) (FinanceSummaryRow, error)
	GetBotConversation(ctx context.Context, telegramChatID int64) (BotConversation, error)
	GetCourse(ctx context.Context, arg GetCourseParams) (Course, error)
	GetGroup(ctx context.Context, id uuid.UUID) (Group, error)
	GetInterventionTask(ctx context.Context, id uuid.UUID) (InterventionTask, error)
	GetInviteToken(ctx context.Context, token string) (InviteToken, error)
	GetInvoice(ctx context.Context, arg GetInvoiceParams) (Invoice, error)
	GetLead(ctx context.Context, arg GetLeadParams) (Lead, error)
	GetLessonByGroupDate(ctx context.Context, arg GetLessonByGroupDateParams) (Lesson, error)
	GetOrganizationByID(ctx context.Context, id uuid.UUID) (Organization, error)
	GetOrganizationBySlug(ctx context.Context, slug string) (Organization, error)
	GetPayment(ctx context.Context, arg GetPaymentParams) (Payment, error)
	GetRefreshSessionByHash(ctx context.Context, tokenHash string) (RefreshSession, error)
	GetSalaryRule(ctx context.Context, teacherID uuid.UUID) (SalaryRule, error)
	GetStudent(ctx context.Context, id uuid.UUID) (Student, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	GroupFinanceByPeriod(ctx context.Context, arg GroupFinanceByPeriodParams) ([]GroupFinanceByPeriodRow, error)
	HighRiskStudents(ctx context.Context) ([]Student, error)
	ListActivePlans(ctx context.Context) ([]Plan, error)
	ListActivities(ctx context.Context, arg ListActivitiesParams) ([]Activity, error)
	// NON-RLS: used by the cross-tenant scheduler to iterate every center.
	ListAllOrgIDs(ctx context.Context) ([]uuid.UUID, error)
	// NON-RLS: superadmin center list (full rows; the caller filters out the platform org).
	ListAllOrganizations(ctx context.Context) ([]Organization, error)
	ListAllPlans(ctx context.Context) ([]Plan, error)
	ListAttendanceByStudent(ctx context.Context, studentID uuid.UUID) ([]AttendanceRecord, error)
	ListBranches(ctx context.Context, orgID uuid.UUID) ([]Branch, error)
	ListCourses(ctx context.Context, orgID uuid.UUID) ([]Course, error)
	ListDebtors(ctx context.Context, orgID uuid.UUID) ([]ListDebtorsRow, error)
	ListEnrollmentsByStudent(ctx context.Context, studentID uuid.UUID) ([]Enrollment, error)
	ListExpenses(ctx context.Context, arg ListExpensesParams) ([]Expense, error)
	ListGroups(ctx context.Context) ([]Group, error)
	ListGroupsByTeacher(ctx context.Context, teacherID pgtype.UUID) ([]Group, error)
	ListHomeworkByStudent(ctx context.Context, studentID uuid.UUID) ([]HomeworkRecord, error)
	ListInterventionTasks(ctx context.Context) ([]ListInterventionTasksRow, error)
	ListInvoicesByStudent(ctx context.Context, studentID uuid.UUID) ([]Invoice, error)
	ListLeads(ctx context.Context, orgID uuid.UUID) ([]Lead, error)
	ListLessons(ctx context.Context, arg ListLessonsParams) ([]Lesson, error)
	// NON-RLS: every chat bound to a student (for the weekly survey broadcast).
	ListLinkedChats(ctx context.Context) ([]ListLinkedChatsRow, error)
	ListNotesByStudent(ctx context.Context, studentID uuid.UUID) ([]Note, error)
	ListObstacleOptions(ctx context.Context, orgID uuid.UUID) ([]ObstacleOption, error)
	ListPaymentsByStudent(ctx context.Context, studentID uuid.UUID) ([]Payment, error)
	ListRooms(ctx context.Context, orgID uuid.UUID) ([]Room, error)
	ListSalarySlips(ctx context.Context, arg ListSalarySlipsParams) ([]ListSalarySlipsRow, error)
	ListSignupRequests(ctx context.Context) ([]SignupRequest, error)
	ListStudents(ctx context.Context) ([]Student, error)
	ListStudentsByGroup(ctx context.Context, groupID pgtype.UUID) ([]Student, error)
	ListSurveysByStudent(ctx context.Context, studentID uuid.UUID) ([]Survey, error)
	ListUsers(ctx context.Context) ([]User, error)
	ListUsersByRole(ctx context.Context, role string) ([]User, error)
	LockRefreshSessionByHash(ctx context.Context, tokenHash string) (RefreshSession, error)
	MarkInviteTokenUsed(ctx context.Context, token string) error
	MarkLeadConverted(ctx context.Context, arg MarkLeadConvertedParams) error
	MarkSalarySlipPaid(ctx context.Context, id uuid.UUID) (SalarySlip, error)
	NullGroupForStudents(ctx context.Context, groupID pgtype.UUID) error
	ResolveInterventionTask(ctx context.Context, arg ResolveInterventionTaskParams) (InterventionTask, error)
	RevokeAllUserSessions(ctx context.Context, userID uuid.UUID) error
	RevokeRefreshSession(ctx context.Context, id uuid.UUID) error
	RiskByGroup(ctx context.Context) ([]RiskByGroupRow, error)
	SetBotConversationFlow(ctx context.Context, arg SetBotConversationFlowParams) error
	SetLeadStage(ctx context.Context, arg SetLeadStageParams) (Lead, error)
	SetStudentTelegramChat(ctx context.Context, arg SetStudentTelegramChatParams) error
	SlugExists(ctx context.Context, slug string) (bool, error)
	StudentBalance(ctx context.Context, studentID uuid.UUID) (int64, error)
	TeacherRevenue(ctx context.Context, arg TeacherRevenueParams) (int64, error)
	TopObstacles(ctx context.Context) ([]TopObstaclesRow, error)
	UpdateBranch(ctx context.Context, arg UpdateBranchParams) (Branch, error)
	UpdateCourse(ctx context.Context, arg UpdateCourseParams) (Course, error)
	UpdateEnrollment(ctx context.Context, arg UpdateEnrollmentParams) (Enrollment, error)
	UpdateGroup(ctx context.Context, arg UpdateGroupParams) (Group, error)
	UpdateLead(ctx context.Context, arg UpdateLeadParams) (Lead, error)
	UpdateLesson(ctx context.Context, arg UpdateLessonParams) (Lesson, error)
	// Refresh the reasons on a student's already-open task so it reflects the latest risk drivers
	// (the auto-open insert is idempotent and does NOT update an existing task).
	UpdateOpenTaskReasons(ctx context.Context, arg UpdateOpenTaskReasonsParams) error
	UpdateOrgBilling(ctx context.Context, arg UpdateOrgBillingParams) (Organization, error)
	UpdateOrgPlanStatus(ctx context.Context, arg UpdateOrgPlanStatusParams) (Organization, error)
	UpdatePlan(ctx context.Context, arg UpdatePlanParams) (Plan, error)
	UpdateRoom(ctx context.Context, arg UpdateRoomParams) (Room, error)
	UpdateSignupRequestStatus(ctx context.Context, arg UpdateSignupRequestStatusParams) (SignupRequest, error)
	// General profile edit (name, contact, identity, onboarding, status, mentor). Risk fields and
	// group are updated by their own queries; this leaves them untouched.
	UpdateStudent(ctx context.Context, arg UpdateStudentParams) (Student, error)
	UpdateStudentRisk(ctx context.Context, arg UpdateStudentRiskParams) error
	UpdateTeacher(ctx context.Context, arg UpdateTeacherParams) (User, error)
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
	UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error)
	UpsertSalaryRule(ctx context.Context, arg UpsertSalaryRuleParams) (SalaryRule, error)
}

var _ Querier = (*Queries)(nil)
